### ISSUE TITLE
Unqualified setup script names likely to create name clashes

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvaPy#13]
pvaPy installs setup scripts for posix and C shells in INSTALL_BIN, named setup.sh and setup.csh

Such unqualified names are likely to create name clash situations, especially when trying to package pvaPy, which would install these scripts in a larger directory for binaries.

Would it be better to prefix the names, calling them e.g. pvaPy-setup.\* ?

**Comment by anjohnson** [comment]
When integrating pvaPy into a larger system with a shared set of install directories you may not want to install those two scripts anyway, since all they do is make it easier for the user to set PYTHONPATH. My assumption is that you probably already have a common directory where you install python modules, and that directory should already be in the user's PYTHONPATH anyway.

I'm not objecting to changing the script names which would be trivial to do, but I'm not convinced actually doing that would be the best way of making the software easy to use in this configuration.

**Comment by sveseli** [comment]
This has been implemented. There are two new sets of setup files: the files that setup only PYTHONPATH, and the files that also setup PATH (for version of python pvaPy has been built with)and LD_LIBRARY_PATH (for boost and python libraries that pvaPy has been built with). The new setup files have pvapy in their names:

bluegill2> ls -ltr bin/linux-x86_64/
total 16
-rw-r--r-- 1 sveseli xsdsdm 316 Mar 27 12:31 pvapy_setup_pythonpath.2.7.sh
-rw-r--r-- 1 sveseli xsdsdm 820 Mar 27 12:31 pvapy_setup_full.2.7.sh
-rw-r--r-- 1 sveseli xsdsdm 319 Mar 27 12:31 pvapy_setup_pythonpath.2.7.csh
-rw-r--r-- 1 sveseli xsdsdm 825 Mar 27 12:31 pvapy_setup_full.2.7.csh

This is now on the pvapy master branch, and will be in 1.1.0 release.
