### ISSUE TITLE
autoconf: V4 tests expect bundle version, but checks the pvAccess module version

### ISSUE THREAD

**Issue by ralphlange** [epics-base/pvaPy#15]
The pvaPy autoconf magic seems to look for the EPICS V4 bundle version (it calls it "EPICS4 version" and expects it to be >=4.4.0), while pvAccess has the pvAccess module version number in the file `pvaVersionNum.h` (currently 4.1.2 on the 4.1 release branch).

**Comment by anjohnson** [comment]
I'm in the middle of fixing this, replacing the grep stuff with C/C++ code. I discovered yesterday that the master branch was still building against the release branches of the V4 modules because the jenkins build scripts hadn't been edited to set the branch names to empty. That broke the build, so I thought I might as well fix the autoconf scripts properly at the same time.

**Comment by ralphlange** [comment]
The problem is that afaik there is no well-defined place for the bundle version. (And I don't know if there should be.)

pvaPy should probably check the module versions of the modules it depends on.

**Comment by dhickin** [comment]
I don't think there should. Modules like pvaPy should build against revs of the dependent modules (pvData, pvAccess etc.) or preferably should behave like the other modules and have master build against master and the release branches build against release branches.
