### ISSUE TITLE
Compilation without EPICSv4

### ISSUE THREAD

**Issue by MichaelWedel** [epics-base/pvaPy#23]
While trying the examples listed in the Readme I realized it's possible to use pvaPy not only for pvAccess, but also for ChannelAccess. I like the interface of the library even for use with CA. Do you think it would at all be possible to compile a "CA-only"-version of pvaPy, i.e. without EPICSv4 available at compile and/or run time? Features that depend on v4 would of course not be available.

The reason I'm asking is that it would be nice to start using pvaPy in scenarios where only EPICSv3 is available. Later on, as more setups transition to EPICSv4, the Python interface would still be the same and the transition on that end would be easier.

I have not made any attempts at this myself, I wanted to hear your opinion first. I hope it's not too crazy of a question.

**Comment by anjohnson** [comment]
No, pvaPy interfaces only to the V4 C++ libraries. The ability to talk CA exists because those V4 libraries also include a copy of libCa and the code needed to use it as well as the pvAccess networking, but that is mostly hidden from pvaPy. The APIs that the pvaPy code calls are pure V4, and it wouldn't be practical to try and change that.

If you prefer this API to the pyepics one you can of course use it for interfacing to CA, although the peak performance might not be quite as good as a pure CA module.

**Comment by MichaelWedel** [comment]
Okay, indeed it doesn't sound practical at all. As you say, in scenarios where V4 is available it's no problem to use pvaPy for CA anyway.

Thanks for getting back to me so quickly and for clarifying!
